### ISSUE TITLE
Timeout integration for the (future) command `/mute`

### ISSUE THREAD

**Issue by MasterPancakes** [raidprotect/raidprotect#75]
For the command `/mute` that I hope will happen, it would be necessary to integrate the Discord timeout (instead of being at 60 seconds, 5 minutes, 10 minutes, 1 hour, 1 day or a week, the command can mute a member up to 27 (or 28 I don’t remember) days with timeout functionality. (27 or 28 days is the maximum number of timeouts).
If we want to make mute permanently (without a predefined date) or more than 27/28 days, this will add the role of mute (classic) to a member.

**Comment by MasterPancakes** [comment]
Or we can add a `/mute` command and a `/timeout` command separately.

**Comment by baptiste0928** [comment]
Thanks for these suggestions! :grinning: 

The bot will initially use timeouts, it is simpler to implement and does not require any setup for users. I don't think there is a real need for longer mutes, since bans are generally preferred for longer sanctions. It may be later considered if many users request this feature.

**Comment by baptiste0928** [comment]
See #113
